# Generated by Django 3.1.4 on 2021-02-25 15:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210223_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Содержание'),
        ),
    ]
